version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 192.168.5.71:5000/apache-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LOG_DIRS=/kafka/kafka-logs

  spark:
    image: 192.168.5.71:5000/spark:latest
    container_name: spark
    ports:
      - "8080:8080"
    command: >
      bash -c "start-master.sh && start-worker.sh spark://spark:7077"
    environment:
      - SPARK_MASTER_HOST=spark
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1G

  iot-producer:
    image: 192.168.5.71:5000/iot-producer:latest
    container_name: iot-producer
    depends_on:
      - kafka
    command: >
      python3 /app/iotProducer.py
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - TOPIC_NAME=iot-data
