---
#
# Author: Aniruddha Gokhale
# CS4287/5287 Principles of Cloud Computing
# Created: Fall 2024
#
# Purpose: 
#   This playbook can be used if you would like to try doing
#   the actions from the master playbook step by step. Simply
#   copy the next play from the master to here and execute
#   just this play and make sure it is working. If everything
#   works correctly, you may then terminate your VMs once again
#   and just run the master playbook end to end
#

#####################################################
### Play 5: Install Docker on our Cloud VMs
#
#####################################################
# - name: "Play 5 - Install Docker on Cloud VMs"
#   hosts: CloudVMs   # specified in the Inventory file
#   remote_user: "{{ cloud_user }}" # since this play operates on the cloud
#                                   # VMs, the user on those VMs is the
#                                   # cloud_user variable
#   gather_facts: yes   # we will need to get variety of facts like arch, OS release
#   become: true  # we set it here instead of doing per task
#   collections:
#   - ansible-base

#   tasks:    # the task to be performed
#   - import_tasks: tasks/playbook_install_docker.yaml

#   handlers:
#   - name: restart containerd
#     systemd:
#       name: containerd
#       state: restarted
#   - name: restart docker
#     systemd:
#       name: docker
#       state: restarted

# - name: "Play 7 - Handle Firewalld policies"
#   hosts: CloudVMs   # specified in the Inventory file
#   remote_user: "{{ cloud_user }}" # since this play operates on the cloud
#                                   # VMs, the user on those VMs is the
#                                   # cloud_user variable
#   become: true  # we set it here instead of doing per task unless
#                 # there is a need to use non-sudo for any subtask
#   gather_facts: false
#   collections:
#   - ansible-base
#   - community.general

#   tasks:    # the task to be performed
#   - import_tasks: tasks/playbook_set_firewalld_rules.yaml

#####################################################
### Play 3: Get facts from Cloud VM
#
# In this play, you must retrieve various facts of the
# VMs you have created. The most important are their
# private IP addresses that you will need in subsequent
# plays
#####################################################
- name: "Play 3: Perform fact gathering on all Cloud VMs"
  hosts: LocalMC  # specified in the Inventory file
  remote_user:  "{{ local_user }}"

  gather_facts: no
  vars:
    vm_name_prefix: "{{ vm_name_prefix }}"
  become: false
  collections:
  - ansible-base
  - openstack.cloud.collection

  tasks:    # the task to be performed
  # @@ You have to write the following child playbook @@
  - import_tasks: tasks/playbook_retrieve_facts_vms.yaml

  
###################################################
# Play 9: Set Kubernetes Master VM
###################################################

- name: "Play 9 - Set Kubernetes master VM"
  hosts: "{{ groups['CloudVMs'][0] }}"  # specified in the Inventory file
  remote_user: "{{ cloud_user }}" # since this play operates on the cloud
                                  # VMs, the user on those VMs is the
                                  # cloud_user variable
  become: true  # we set it here instead of doing per task unless
                # there is a need to use non-sudo for any subtask
  gather_facts: false
  collections:
  - ansible-base
  - community.general

  tasks:    # the task to be performed
  - import_tasks: tasks/playbook_set_k8_master_node.yaml



...

