--- 
- name: Set masterVM variable 
  set_fact:
    masterVM: "{{ groups['CloudVMs'][0] }}" 

- name: Reset Kubernetes cluster (if any)
  command: kubeadm reset -f
  ignore_errors: true

- name: Remove Kubernetes manifests
  file:
    path: /etc/kubernetes/manifests
    state: absent

- name: Ensure etcd data directory is absent
  file:
    path: /var/lib/etcd
    state: absent

- name: Kill processes using ports 10250, 2379, and 2380 (if necessary)
  shell: |
    for port in 10250 2379 2380; do
      lsof -ti :$port | xargs -r sudo kill -9
    done
  ignore_errors: true

- name: Install Kubernetes components using snap
  ansible.builtin.shell: |
    snap install kube-apiserver kube-scheduler kube-controller-manager

- name: Initialize the Kubernetes cluster on Master node
  shell: kubeadm init --apiserver-advertise-address={{ ansible_host }} --pod-network-cidr=10.244.0.0/16
  register: kubeadm_output

- name: Copy admin kubeconfig to user .kube directory
  shell: |
    mkdir -p /home/{{ ansible_user }}/.kube
    cp /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config
    chown {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/.kube/config
  when: kubeadm_output.changed

- name: Create kube config directory for non-root user
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: '0755'

- name: Set ownership for .kube/config
  file:
    path: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user | default('your-username') }}"
    group: "{{ ansible_user | default('your-username') }}"
    mode: '0644'
  when: kubeadm_output.changed

- name: Display join command
  debug:
    msg: "{{ kubeadm_output.stdout_lines | select('search', 'kubeadm join') | list }}"
